# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-4MphATWqp4DR744qiuQv4R09Kxgv9E
"""

import pandas as pd
df =pd.DataFrame()
df['Name']=['abc','xyz','pqr','uwx','xyz']
df['age']=[38,25,19,33,68]
df['sex']=['m','f','m','f','f']
df.iloc[1:4]
df[(df['sex']=='f') &(df['age']>=65)]
df.replace("f","F")
df.replace("m","M")
print(df['age'].count())
print(df['sex'].unique())
print(df['sex'].value_counts())
df.drop(df.columns[1],axis=1)